<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>APRC.Core.Domain.Model</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <ProjectReference Include="..\APRC.Core.SharedKernel.Abstractions\APRC.Core.SharedKernel.Abstractions.csproj" />
  </ItemGroup>

</Project>
