<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>APRC.Presentation.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\APRC.Core.AppService\APRC.Core.AppService.csproj" />
    <ProjectReference Include="..\..\Core\APRC.Core.Domain.Model\APRC.Core.Domain.Model.csproj" />
    <ProjectReference Include="..\..\Core\APRC.Core.Domain.Service\APRC.Core.Domain.Service.csproj" />
    <ProjectReference Include="..\..\Infrastructure\APRC.Infrastructure\APRC.Infrastructure.csproj" />
  </ItemGroup>

</Project>
